name: Starter Web App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Create MSDeploy package
      run: dotnet msbuild ./StarterWebApp.csproj /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PackageLocation=./publish/msdeploy.zip
